Staging Push 1021 - PIV Authentication Troubleshooting and Identifiers
GSA/ficam-playbooks pull request #281
Opened 2021-10-21 20:24 UTC by maxwellfunk

Closes #82, Closes #84 

All information was added to the PIV playbook.  

Added RFC822 in SAN reference to the PIV identifiers page per input from Todd on issue #84, and added much more information to network authentication troubleshooting to include CAPI2 screenshots on issue #82.

2021-10-22 10:42 UTC, JBPayne007 approved these changes

2021-10-26 16:30 UTC, idmken commented on _data/navigation.yml
> +  - text: Troubleshooting PIV Auth Issues
I updated this. using "common" made it seem like it was related to COMMON.

2021-10-26 16:47 UTC, idmken requested changes
@rsherwood-gsa @maxwellfunk Audience for this seems like an admin who is trying to troubleshoot PIV authentication errors. Please update based on my comments and do an overall plain language review.

2021-10-26 16:47 UTC, idmken commented on _piv/network/13_common_issues.md
> +   - Domain Controller (Host)
You've outlined two major types of troubleshooting steps. I'd expect to see steps related to teach major area below to investigate. I don't see this. @rsherwood-gsa

2021-10-26 16:47 UTC, idmken commented on _piv/network/13_common_issues.md
> +In these instances you may want to view the other end-entity certificate on the opposite machine and check the certifiation path to determine if there are errors in path validation.  If errors are en
This is confusing. "view the other certs on the opposite machine"? If the audience for this is someone troubleshooting an authentication error. I'd expect to see steps. step 1 check here. step 2 check here. Or a list of common errors and what error they relate to. For example, a "smart card authentication is not supported" error message related to error code xx in the event viewer and related to domain authentication or a GPO, etc.

2021-10-26 16:47 UTC, idmken commented on _piv/network/13_common_issues.md
> +## Network Misconfigurations
Make this clearer that "sometimes network rules restrict access to PKI necessary locations for revocation checking". Link to COmmon playbook or network tuning on how to check your machine can access the appropriate URL.

2021-10-26 16:47 UTC, idmken commented on _piv/network/13_common_issues.md
> +## Account Linking
Plain language this . "the AD account name must match the UPN in the PIV card. If it doesn't you may see xx error with error code xx in the event log on the workstation and domain controller. Go this xx log in the event viewer and look for error code xx. Reference our account linking page for instructions on account linking or this technet article on xx".

2021-10-26 16:47 UTC, idmken commented on _piv/network/13_common_issues.md
> +   - Domain Controller (Host)
Based on this list, I would expect to see below sections on.
1. domain controller or workstation unable to validate PIV certificate (network misconfiguration)
2. NTAuth misconfigurations (trust stores?)
3. domain controller certificate validation (?)

Should add account linking under domain controller issues to match the below.

2021-10-26 16:47 UTC, idmken commented on _piv/network/13_common_issues.md
> +
expecting to see remediation steps related to domain controller certificate errors.
- typical errors either in the GUI or event view.
- Playbook or technet links.

2021-10-26 16:47 UTC, idmken commented on _piv/network/13_common_issues.md
> +Microsoft Windows based systems have the ability to record logs associated with PKI and X.509 based events, called CryptoAPI v2.0 or CAPI2.  This utility can be very helpful when enabled on a domain
What are the different errors an admin would see between the domain controller and the workstation and why would someone look at one vs the other?

2021-10-27 15:40 UTC, idmken requested changes

2021-10-27 15:40 UTC, idmken commented on _piv/5_piv_identifiers.md
> +| User Principal Name in _Subject Alternative Name_   |  Unique within a given domain; Not required to be included in all PIV Authentication certificates; Not recommended for use as an identifier to
If this addition to to answer the question "what breaks without UPN", it doesn't answer that.

2021-10-27 16:02 UTC, maxwellfunk commented on _piv/5_piv_identifiers.md
> +| User Principal Name in _Subject Alternative Name_   |  Unique within a given domain; Not required to be included in all PIV Authentication certificates; Not recommended for use as an identifier to
Given Todd's comments on the issue, I think the scope of the issue from 2016 has changed perspective.  Most web-applications are looking for an identifier that might be from an external domain that also provides user validation capability.  As a result, the preference for RFC822 email would seem to be more practical guidance for modern issues.  A UPN of 1234567890@mail.mil (e.g. a DoD EDIPI based UPN may not even be used).  Additionally, we received no feedback on what web platforms break in any instance.

2021-10-27 16:10 UTC, maxwellfunk commented on _piv/network/13_common_issues.md
> +Microsoft Windows based systems have the ability to record logs associated with PKI and X.509 based events, called CryptoAPI v2.0 or CAPI2.  This utility can be very helpful when enabled on a domain
> @rsherwood-gsa @maxwellfunk Audience for this seems like an admin who is trying to troubleshoot PIV authentication errors. Please update based on my comments and do an overall plain language review.

Due to the potential for the client to be unable to validate a DC cert in a mutual authentication scenario, I think the intended audience is actually broader.

2021-10-28 12:51 UTC, JillTunick commented
@maxwellfunk and @rsherwood-gsa, after you've made the content additions/changes that Ken requested, please tag me so I can do plain language review and editing on the page. Thanks in advance.

2021-11-08 16:59 UTC, rsherwood-gsa commented
@idmken, based on our chat on Friday, I have tried to do some restructuring of piv-auth-issues to have a page flow - there is in introductory section and then some sub-bullets that organize the material. A lot of work to do in the details to address your comments, but do you like the structure I have proposed?

2021-11-09 14:28 UTC, closed without merging