0329 PDVAL and PIV Logon Troubleshooting
GSA/ficam-playbooks pull request #468
Opened 2022-03-30 18:13 UTC by idmken

Fixes #208 - Create section on PDVAL
Fixes #84 - Did not identify breaks when not using UPN.
Fixes #82 - Includes basic guide on PIV Logon troubleshooting
Fixes #398 - Documented

2022-03-30 19:03 UTC, JillTunick requested changes
The PIV-I page looks great. 

In the PDVAL page, in the Informative status box, the link doesn't work in Federalist preview. I went into the markdown page in the branch to see if I could fix it, but I don't know enough about HTML coding to fix that type of HTML link and I didn't want to screw it up. I have attached screenshots of the link that doesn't work and the coding in the markdown page.
![PDVAL Info Status box](https://user-images.githubusercontent.
![PDVAL link doesn't work in preview](https://user-images.githubusercontent.com/88543325/160911081-7e1583b8-85f7-48fc-a248-326486f4164d.JPG)
com/88543325/160911062-734a9c56-c818-4a54-adea-10336ea59bb5.JPG)

2022-03-30 20:58 UTC, idmken commented
> Details

I fixed it. Needed to remove the ( ) from the link.

2022-03-31 10:03 UTC, JBPayne007 approved these changes

2022-03-31 13:08 UTC, JillTunick approved these changes
The PDVAL page looks great and all the links work now. Thanks for fixing that coding in the Info Status box, Ken.

2022-03-31 17:02 UTC, merged